### ISSUE TITLE
Function `evaluate_scores` not found

### ISSUE THREAD

**Issue by blurgyy** [LgQu/DPT-T2I#6]
Hi, very solid work!

I tried to run `train_stage1.py`, but it raises an `ImportError` while trying to import `evaluate_scores` from `utils.py`.  I searched the name across the codebase but found no function definition.  Could you please provide the missing code?

Best regards

**Comment by LgQu** [comment]
Hi, 

Thanks for your interest in this work. `evaluate_scores` is not actually used in the following code, so you can delete it and continue to run. I have modified `train_stage1.py` and deleted it as well.

**Comment by blurgyy** [comment]
Hi @LgQu, thanks for the feedback!

I actually noticed that `train_stage1.py` does not directly call `evaluate_scores` and tried removing the function from `train_stage1.py`, but upon trying to run the code, `evaluate_scores` is still called inside the `eval_acc` function imported from `utils.py`.

I suppose I can again remove calls to `eval_acc` and all the metrics depending on its outputs, but it would be the best if you can provide with the relevant code, if that's possible from your side.

Best regards
